# 视频设置
video:
  width: 1280
  height: 720
  fps: 30
  device: 0

# 检测设置
detection:
  confidence: 0.6
  nms_threshold: 0.3
  model: "body_25"

# 背景设置
background:
  blur_strength: 5
  virtual_enabled: true
  default_background: "static/img/default_bg.jpg"

# 服务器设置
server:
  host: "0.0.0.0"
  port: 5000
  debug: false