version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/venv
      - /app/__pycache__
    environment:
      - FLASK_ENV=development
      - PYTHONPATH=/app
    restart: unless-stopped